kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic-pvc
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
